version: '3.1'
services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: SWOOLE
      MYSQL_ROOT_PASSWORD: MYSQLPASS
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8880:80
  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    ports:
      - '9501:9501'
    volumes:
      - ./:/app
